In [1]:
import numpy as np
import matplotlib as mp

In [2]:
#Exponantial Function#
a=np.array([1,2,3])
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]


In [4]:
#Logarithmic Function log=loge and log10=log10#
a=np.array([1,2,3])
print(np.log(a))
print(np.log10(a))

[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
