In [2]:
import numpy as np

In [3]:
#Find dimension of the array#
a=np.array([(2,5,7),(1,0,8),(1,2,3)])
print(a.ndim)
print(a)

2
[[2 5 7]
 [1 0 8]
 [1 2 3]]


In [6]:
#Find byte size of an element in the array#
a=np.array([(2,5,7),(1,0,8),(1,2,3)])
print(a.itemsize)

4


In [7]:
#Find datatype of an element in the array#
a=np.array([(2,5,7),(1,0,8),(1,2,3)])
print(a.dtype)

int32


In [11]:
#Find size of an array#
a=np.array([(2,5,7),(1,0,8),(1,2,3)])
print(a.size)
print(a.shape)

9
(3, 3)


In [9]:
#Find shape of an array#
a=np.array([(2,5,7),(1,0,8),(1,2,3)])
print(a.shape)

(3, 3)


In [4]:
#Reshapeing of an array#
a=np.array([(2,5,7),(1,0,8)])
print(a.reshape(3,2))
print(a.reshape(6,1))

[[2 5]
 [7 1]
 [0 8]]
[[2]
 [5]
 [7]
 [1]
 [0]
 [8]]


In [12]:
#Slicing of an array#
a=np.array([(2,5,7),(1,0,8)])
print(a[0:,2])
a=np.array([(2,5,7),(1,0,8),(1,2,3)])
print(a[0:2,2])
a=np.array([(2,5,7),(1,0,8),(1,2,3)])
print(a[0:,2])

[7 8]
[7 8]
[7 8 3]


In [10]:
#Max,Min and Sum of an array#
a=np.array([[2,5,7],[1,0,8]])
print(a.max())
print(a.min())
print(a.sum())

8
0
23


In [21]:
#Axis operation in array axis=0 for rows and axis=1 for columns#
a=np.array([(2,5,7),(1,0,8)])
print(a.sum(axis=0))
print(a.sum(axis=1))

[ 3  5 15]
[14  9]


In [14]:
#Square root of an array#
a=np.array([(2,5,7),(1,0,8)])
print(np.sqrt(a))

[[1.41421356 2.23606798 2.64575131]
 [1.         0.         2.82842712]]


In [15]:
#Standard Deviation of an array#
a=np.array([(2,5,7),(1,0,8)])
print(np.std(a))

3.0230595245361758


In [16]:
#Airthematic operations on an array#
a=np.array([(2,5,7),(1,0,8)])
b=np.array([(2,5,7),(1,0,8)])
print(a+b)

[[ 4 10 14]
 [ 2  0 16]]


In [7]:
#Concatination of arrays vertical and horizantal stacking#
a=np.array([(2,5,7),(1,0,8)])
b=np.array([(2,6,7),(1,0,8)])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

#To put all the elements of an array into single dimension#
print(np.ravel(a))

[[2 5 7]
 [1 0 8]
 [2 6 7]
 [1 0 8]]
[[2 5 7 2 6 7]
 [1 0 8 1 0 8]]
[2 5 7 1 0 8]
